# NumPy

In [1]:
number_list = [1,1,2,2,3,3]
print(number_list)

[1, 1, 2, 2, 3, 3]


In [2]:
import numpy as np

In [5]:
number_array = np.array(number_list)
print(number_array)
number_array

[1 1 2 2 3 3]


array([1, 1, 2, 2, 3, 3])

In [25]:
number_array.shape

(6,)

In [26]:
number_array.dtype

dtype('int64')

In [7]:
number_2D_list = [[1,1],[1,2],[2,1],[2,2]]
print(number_2D_list)

[[1, 1], [1, 2], [2, 1], [2, 2]]


In [8]:
number_2D_array = np.array(number_2D_list)
print(number_2D_array)
number_2D_array

[[1 1]
 [1 2]
 [2 1]
 [2 2]]


array([[1, 1],
       [1, 2],
       [2, 1],
       [2, 2]])

In [24]:
number_2D_array.shape

(4, 2)

In [13]:
np.zeros(2)

array([0., 0.])

In [14]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [20]:
number_array.max()

3

In [21]:
number_array.min()

1

In [22]:
number_array.argmax()

4

In [23]:
number_array.argmin()

0

In [50]:
number_array.sum()

12

In [51]:
number_array.mean()

2.0

In [52]:
number_2D_array.sum(axis=0)

array([6, 6])

In [53]:
number_2D_array.sum(axis=1)

array([2, 3, 3, 4])

In [54]:
number_2D_array.sum()

12

In [29]:
number_array[4]

3

In [31]:
number_array[4:6]

array([3, 3])

In [32]:
number_array[:]

array([1, 1, 2, 2, 3, 3])

In [34]:
number_2D_array[0]

array([1, 1])

In [36]:
number_2D_array[1][1]

2

In [40]:
number_2D_array[1,1]

2

In [43]:
number_2D_array[:2,:2]

array([[1, 1],
       [1, 2]])

In [44]:
number_2D_array[1,:]

array([1, 2])

In [46]:
number_2D_array >= 2

array([[False, False],
       [False,  True],
       [ True, False],
       [ True,  True]])

In [49]:
tf = number_2D_array >= 2
number_2D_array[tf]

array([2, 2, 2, 2])

array([2, 2, 2, 2])